// <auto-generated />
using System;
using CagriMerkeziUyg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CagriMerkeziUyg.Migrations
{
    [DbContext(typeof(CagriMerkeziDbContext))]
    [Migration("20250823132145_OperatorPerformansSystem")]
    partial class OperatorPerformansSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri adı");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Müşteri adresi");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2")
                        .HasComment("Müşteri doğum tarihi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Müşteri e-posta adresi");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kayıt oluşturulma tarihi");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Müşteri hakkında notlar");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri soyadı");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Müşteri telefon numarası");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Musteriler_Email");

                    b.HasIndex("TelefonNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Musteriler_TelefonNo");

                    b.ToTable("Musteriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            Adres = "İstanbul, Türkiye",
                            DogumTarihi = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Düzenli müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Yılmaz",
                            TelefonNo = "05551234567"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Adres = "Ankara, Türkiye",
                            DogumTarihi = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Yeni müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Kaya",
                            TelefonNo = "05559876543"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("CagriSuresi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriMemnuniyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Oncelik")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId");

                    b.ToTable("MusteriAktiviteleri", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("CalismaSaatiBaslangic")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CalismaSaatiBitis")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonGiris")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_Email");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_KullaniciAdi");

                    b.ToTable("Operatorler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "admin@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            Soyad = "User",
                            Telefon = "05551111111"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mehmet",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 9, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 0, 0, 0),
                            Email = "mehmet@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "mehmet.demir",
                            Rol = "Operator",
                            Soyad = "Demir",
                            Telefon = "05552222222"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fatma",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 30, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 30, 0, 0),
                            Email = "fatma@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "fatma.ozkan",
                            Rol = "Supervisor",
                            Soyad = "Özkan",
                            Telefon = "05553333333"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AktifCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CozulenCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MusteriMemnuniyetPuani")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrtalamaCagriSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PerformansPuani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamMolaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("Tarih");

                    b.ToTable("OperatorPerformansKayitlari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("PerformansKayitlari")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Navigation("Aktiviteler");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("PerformansKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
