// <auto-generated />
using System;
using CagriMerkeziUyg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CagriMerkeziUyg.Migrations
{
    [DbContext(typeof(CagriMerkeziDbContext))]
    [Migration("20251001151102_RandevuSistemiEklendi")]
    partial class RandevuSistemiEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CagriMerkeziUyg.Models.AramaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriMemnuniyet")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<double?>("Sure")
                        .HasColumnType("float");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaslangicZamani");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TelefonNo");

                    b.ToTable("AramaLoglari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri adı");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Müşteri adresi");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2")
                        .HasComment("Müşteri doğum tarihi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Müşteri e-posta adresi");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kayıt oluşturulma tarihi");

                    b.Property<int?>("MusteriTipi")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Müşteri hakkında notlar");

                    b.Property<string>("OzelNotlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri soyadı");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Müşteri telefon numarası");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Musteriler_Email");

                    b.HasIndex("TelefonNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Musteriler_TelefonNo");

                    b.ToTable("Musteriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            Adres = "İstanbul, Türkiye",
                            DogumTarihi = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Düzenli müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Yılmaz",
                            TelefonNo = "05551234567"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Adres = "Ankara, Türkiye",
                            DogumTarihi = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Yeni müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Kaya",
                            TelefonNo = "05559876543"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("CagriSuresi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriMemnuniyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Oncelik")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId");

                    b.ToTable("MusteriAktiviteleri", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Etiket atama tarihi");

                    b.Property<int?>("AtayanOperatorId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriEtiketiId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Atama notları");

                    b.HasKey("Id");

                    b.HasIndex("AtamaTarihi");

                    b.HasIndex("AtayanOperatorId");

                    b.HasIndex("MusteriEtiketiId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("MusteriId", "MusteriEtiketiId")
                        .IsUnique()
                        .HasDatabaseName("IX_MusteriEtiketAtamalari_MusteriId_MusteriEtiketiId");

                    b.ToTable("MusteriEtiketAtamalari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Etiket açıklaması");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Etiket adı");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Etiket aktif durumu");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Etiket oluşturulma tarihi");

                    b.Property<string>("RenkKodu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007bff")
                        .HasComment("Etiket renk kodu");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_MusteriEtiketleri_Ad");

                    b.ToTable("MusteriEtiketleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Yüksek değerli müşteriler",
                            Ad = "VIP Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#FFD700"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Düzenli olarak hizmet alan müşteriler",
                            Ad = "Düzenli Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#28a745"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Yeni kayıt olan müşteriler",
                            Ad = "Yeni Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#17a2b8"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Dikkatli yaklaşılması gereken müşteriler",
                            Ad = "Riskli Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#dc3545"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Sık sık şikayet eden müşteriler",
                            Ad = "Şikayetçi Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#fd7e14"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Hizmetlerden memnun olan müşteriler",
                            Ad = "Memnun Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#6f42c1"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kurumsal müşteriler",
                            Ad = "Kurumsal Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#20c997"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Bireysel müşteriler",
                            Ad = "Bireysel Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#6c757d"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("CalismaSaatiBaslangic")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CalismaSaatiBitis")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SonGiris")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_Email");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_KullaniciAdi");

                    b.ToTable("Operatorler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "admin@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            Sifre = "admin123",
                            Soyad = "User",
                            Telefon = "05551111111"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mehmet",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 9, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 0, 0, 0),
                            Email = "mehmet@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "mehmet.demir",
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Demir",
                            Telefon = "05552222222"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fatma",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 30, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 30, 0, 0),
                            Email = "fatma@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "supervisor",
                            Rol = "Supervisor",
                            Sifre = "super123",
                            Soyad = "Özkan",
                            Telefon = "05553333333"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ali",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 9, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "ali@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "operator1",
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Kaya",
                            Telefon = "05554444444"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Zeynep",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 30, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 30, 0, 0),
                            Email = "zeynep@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "operator2",
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Çelik",
                            Telefon = "05555555555"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AktifCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CozulenCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MusteriMemnuniyetPuani")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrtalamaCagriSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PerformansPuani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamMolaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("Tarih");

                    b.ToTable("OperatorPerformansKayitlari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Randevu açıklaması");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Randevu başlığı");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2")
                        .HasComment("Randevu bitiş zamanı");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Bekliyor")
                        .HasComment("Randevu durumu");

                    b.Property<bool>("HatirlatmaAktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Hatırlatma aktif mi");

                    b.Property<bool>("HatirlatmaGonderildi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Hatırlatma gönderildi mi");

                    b.Property<int>("HatirlatmaSuresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15)
                        .HasComment("Hatırlatma süresi (dakika)");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanOperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Randevu oluşturulma tarihi");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Normal")
                        .HasComment("Randevu önceliği");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuZamani")
                        .HasColumnType("datetime2")
                        .HasComment("Randevu tarihi ve saati");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("TamamlanmaNotu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Tamamlanma notu");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Randevu tipi");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_Randevular_Durum");

                    b.HasIndex("MusteriId")
                        .HasDatabaseName("IX_Randevular_MusteriId");

                    b.HasIndex("OlusturanOperatorId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("IX_Randevular_OperatorId");

                    b.HasIndex("RandevuZamani")
                        .HasDatabaseName("IX_Randevular_RandevuZamani");

                    b.HasIndex("RandevuZamani", "OperatorId")
                        .HasDatabaseName("IX_Randevular_RandevuZamani_OperatorId");

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.AramaLog", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketAtama", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "AtayanOperator")
                        .WithMany()
                        .HasForeignKey("AtayanOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.MusteriEtiketi", "MusteriEtiketi")
                        .WithMany("MusteriEtiketAtamalari")
                        .HasForeignKey("MusteriEtiketiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany("EtiketAtamalari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtayanOperator");

                    b.Navigation("Musteri");

                    b.Navigation("MusteriEtiketi");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("PerformansKayitlari")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Randevu", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "OlusturanOperator")
                        .WithMany()
                        .HasForeignKey("OlusturanOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("OlusturanOperator");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("EtiketAtamalari");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketi", b =>
                {
                    b.Navigation("MusteriEtiketAtamalari");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("PerformansKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
