// <auto-generated />
using System;
using CagriMerkeziUyg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CagriMerkeziUyg.Migrations
{
    [DbContext(typeof(CagriMerkeziDbContext))]
    [Migration("20250805125944_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri adı");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Müşteri adresi");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2")
                        .HasComment("Müşteri doğum tarihi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Müşteri e-posta adresi");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kayıt oluşturulma tarihi");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Müşteri hakkında notlar");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri soyadı");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Müşteri telefon numarası");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Musteriler_Email");

                    b.HasIndex("TelefonNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Musteriler_TelefonNo");

                    b.ToTable("Musteriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            Adres = "İstanbul, Türkiye",
                            DogumTarihi = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Düzenli müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Yılmaz",
                            TelefonNo = "05551234567"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Adres = "Ankara, Türkiye",
                            DogumTarihi = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse@email.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Yeni müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Kaya",
                            TelefonNo = "05559876543"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
