// <auto-generated />
using System;
using CagriMerkeziUyg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CagriMerkeziUyg.Migrations
{
    [DbContext(typeof(CagriMerkeziDbContext))]
    partial class CagriMerkeziDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CagriMerkeziUyg.Models.AramaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CagriSirasindaKayitOlusturuldu")
                        .HasColumnType("bit");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<bool>("MusteriKayitliydi")
                        .HasColumnType("bit");

                    b.Property<int?>("MusteriMemnuniyet")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<double?>("Sure")
                        .HasColumnType("float");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaslangicZamani");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TelefonNo");

                    b.ToTable("AramaLoglari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Kategori açıklaması");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Kategori adı");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Kategori aktif mi");

                    b.Property<string>("AktiviteTuru")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Hangi aktivite türü için (null ise tümü)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Font Awesome icon sınıfı");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kategori oluşturulma tarihi");

                    b.Property<string>("RenkKodu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007bff")
                        .HasComment("Kategori renk kodu (HEX)");

                    b.Property<int>("Sira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Gösterim sırası");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .HasDatabaseName("IX_CevapSablonKategorileri_Ad");

                    b.HasIndex("Aktif")
                        .HasDatabaseName("IX_CevapSablonKategorileri_Aktif");

                    b.HasIndex("Sira")
                        .HasDatabaseName("IX_CevapSablonKategorileri_Sira");

                    b.ToTable("CevapSablonKategorileri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Çağrı başlangıcı ve bitiş mesajları",
                            Ad = "Karşılama & Veda",
                            Aktif = true,
                            IconClass = "fa-hand-wave",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#28a745",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Ürün özellikleri, fiyat, stok bilgileri",
                            Ad = "Ürün & Hizmet Bilgisi",
                            Aktif = true,
                            IconClass = "fa-box",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#007bff",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "İade süreci, iptal talepleri",
                            Ad = "İade & İptal",
                            Aktif = true,
                            IconClass = "fa-undo",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#dc3545",
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Sipariş takibi, teslimat bilgileri",
                            Ad = "Sipariş & Teslimat",
                            Aktif = true,
                            IconClass = "fa-truck",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#fd7e14",
                            Sira = 4
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Sorun giderme, kurulum yardımı",
                            Ad = "Teknik Destek",
                            Aktif = true,
                            IconClass = "fa-tools",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#6f42c1",
                            Sira = 5
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Ödeme yöntemleri, fatura talepleri",
                            Ad = "Ödeme & Fatura",
                            Aktif = true,
                            IconClass = "fa-credit-card",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#20c997",
                            Sira = 6
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Şikayet alma ve yönetme",
                            Ad = "Şikayet Yönetimi",
                            Aktif = true,
                            AktiviteTuru = "Sikayet",
                            IconClass = "fa-exclamation-triangle",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#ffc107",
                            Sira = 7
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonKullanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktiviteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KullanimTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kullanım tarihi");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktiviteId");

                    b.HasIndex("KullanimTarihi")
                        .HasDatabaseName("IX_CevapSablonKullanimlar_KullanimTarihi");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("IX_CevapSablonKullanimlar_OperatorId");

                    b.HasIndex("SablonId")
                        .HasDatabaseName("IX_CevapSablonKullanimlar_SablonId");

                    b.HasIndex("SablonId", "KullanimTarihi")
                        .HasDatabaseName("IX_CevapSablonKullanimlar_SablonId_KullanimTarihi");

                    b.ToTable("CevapSablonKullanimlar", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Şablon aktif mi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Şablon başlığı");

                    b.Property<bool>("DegiskenIceriyor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Değişken placeholder içeriyor mu");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Şablon içeriği");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KisaYol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Klavye kısayolu");

                    b.Property<int>("KullanimSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Kaç kez kullanıldı");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Operatör için notlar");

                    b.Property<int?>("OlusturanOperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Şablon oluşturulma tarihi");

                    b.Property<int>("Sira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Kategori içinde sıra");

                    b.Property<DateTime?>("SonKullanimTarihi")
                        .HasColumnType("datetime2")
                        .HasComment("Son kullanım tarihi");

                    b.HasKey("Id");

                    b.HasIndex("Aktif")
                        .HasDatabaseName("IX_CevapSablonlari_Aktif");

                    b.HasIndex("KategoriId")
                        .HasDatabaseName("IX_CevapSablonlari_KategoriId");

                    b.HasIndex("KullanimSayisi")
                        .HasDatabaseName("IX_CevapSablonlari_KullanimSayisi");

                    b.HasIndex("OlusturanOperatorId");

                    b.HasIndex("KategoriId", "Sira")
                        .HasDatabaseName("IX_CevapSablonlari_KategoriId_Sira");

                    b.ToTable("CevapSablonlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Baslik = "Standart Karşılama",
                            DegiskenIceriyor = true,
                            Icerik = "Merhaba, [Şirket Adı] çağrı merkezine hoş geldiniz. Ben {OperatorAdi}, size nasıl yardımcı olabilirim?",
                            KategoriId = 1,
                            KisaYol = "F1",
                            KullanimSayisi = 0,
                            Notlar = "Müşteriye güler yüzle hitap edin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Baslik = "VIP Müşteri Karşılama",
                            DegiskenIceriyor = true,
                            Icerik = "Sayın {MusteriAdi}, hoş geldiniz! Sizi tanıdığımız için çok mutluyuz. Size nasıl yardımcı olabilirim?",
                            KategoriId = 1,
                            KisaYol = "F2",
                            KullanimSayisi = 0,
                            Notlar = "VIP etiketli müşteriler için kullanın",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Baslik = "Standart Veda",
                            DegiskenIceriyor = true,
                            Icerik = "Bize ulaştığınız için teşekkür ederim {MusteriAdi}. İyi günler dilerim!",
                            KategoriId = 1,
                            KisaYol = "F3",
                            KullanimSayisi = 0,
                            Notlar = "Çağrı sonunda kullanın",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            Baslik = "Fiyat Bilgisi",
                            DegiskenIceriyor = true,
                            Icerik = "İlgilendiğiniz ürünün güncel fiyatını size aktarıyorum. Ürün fiyatı: {Fiyat} TL. Kargo ücreti dahildir. Başka bir ürün hakkında bilgi almak ister misiniz?",
                            KategoriId = 2,
                            KullanimSayisi = 0,
                            Notlar = "Fiyat bilgisini güncel sistemden kontrol edin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 5,
                            Aktif = true,
                            Baslik = "Stok Durumu - Var",
                            DegiskenIceriyor = false,
                            Icerik = "İyi haberlerim var! İlgilendiğiniz ürün stoklarımızda mevcut. Hemen sipariş verebilirsiniz. Sipariş vermek ister misiniz?",
                            KategoriId = 2,
                            KullanimSayisi = 0,
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 6,
                            Aktif = true,
                            Baslik = "Stok Durumu - Yok",
                            DegiskenIceriyor = true,
                            Icerik = "Üzgünüm, ilgilendiğiniz ürün şu anda stoklarımızda bulunmuyor. Ancak {TarihTahmini} tarihinde tekrar stoklarımıza gireceğini tahmin ediyoruz. Bilgilendirme için iletişim bilgilerinizi kaydedebilirim.",
                            KategoriId = 2,
                            KullanimSayisi = 0,
                            Notlar = "Tahmini tarihi lojistik ekibinden öğrenin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 3
                        },
                        new
                        {
                            Id = 7,
                            Aktif = true,
                            Baslik = "Standart İade Süreci",
                            DegiskenIceriyor = false,
                            Icerik = "Tabii efendim, iade işleminize yardımcı olabilirim. İade prosedürümüz şu şekildedir:\n\n1. Ürün 14 gün içinde iade edilmelidir\n2. Ürün kullanılmamış ve ambalajı açılmamış olmalıdır\n3. Fatura veya sipariş numarası gereklidir\n\nKargo ücreti cayma hakkı veya hasarlı ürün durumunda tarafımızca karşılanır. Size iade kodu gönderebilirim.",
                            KategoriId = 3,
                            KisaYol = "F4",
                            KullanimSayisi = 0,
                            Notlar = "İade nedeni mutlaka sorun",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 8,
                            Aktif = true,
                            Baslik = "Sipariş İptal",
                            DegiskenIceriyor = true,
                            Icerik = "Sipariş iptal talebinizi aldım. Sipariş numaranız {SiparisNo}. Eğer siparişiniz henüz kargoya verilmediyse iptal edebiliriz. Kargoya verildiyse ürünü teslim almadan iade edebilirsiniz. Kontrol edip size dönüş yapacağım.",
                            KategoriId = 3,
                            KullanimSayisi = 0,
                            Notlar = "Sipariş durumunu sisteme bakıp kontrol edin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 9,
                            Aktif = true,
                            Baslik = "Sipariş Takibi",
                            DegiskenIceriyor = true,
                            Icerik = "Sipariş numaranız: {SiparisNo}\nDurum: {Durum}\nKargo Takip No: {KargoNo}\n\nSiparişiniz {KargoFirmasi} ile gönderilmiştir. Takip numarası ile kargo firmasının web sitesinden detaylı takip yapabilirsiniz.",
                            KategoriId = 4,
                            KisaYol = "F5",
                            KullanimSayisi = 0,
                            Notlar = "Bilgileri sistemden kontrol edin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 10,
                            Aktif = true,
                            Baslik = "Teslimat Süresi",
                            DegiskenIceriyor = false,
                            Icerik = "Siparişiniz onaylandıktan sonra 1-3 iş günü içinde kargoya verilecektir. Kargo süresi bulunduğunuz ile bağlı olarak 2-5 iş günü arasında değişmektedir. Toplam teslimat süresi ortalama 3-8 iş günüdür.",
                            KategoriId = 4,
                            KullanimSayisi = 0,
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 11,
                            Aktif = true,
                            Baslik = "Genel Sorun Giderme",
                            DegiskenIceriyor = false,
                            Icerik = "Yaşadığınız sorunu çözmek için birlikte adım adım ilerleyelim:\n\n1. Cihazı kapatıp 30 saniye bekleyin\n2. Tekrar açın\n3. Sorun devam ediyorsa bağlantı kablolarını kontrol edin\n4. Güncelleme olup olmadığını kontrol edin\n\nBu adımları denedikten sonra durum nasıl?",
                            KategoriId = 5,
                            KullanimSayisi = 0,
                            Notlar = "Sabırlı olun, müşteriye rehberlik edin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 12,
                            Aktif = true,
                            Baslik = "Teknik Ekibe Yönlendirme",
                            DegiskenIceriyor = false,
                            Icerik = "Durumu değerlendirdim ve bu konuda teknik ekibimizin size yardımcı olması daha uygun olacaktır. Bilgilerinizi teknik destek ekibine ileteceğim ve en kısa sürede sizinle iletişime geçeceklerdir. İletişim bilgilerinizi teyit edebilir miyim?",
                            KategoriId = 5,
                            KullanimSayisi = 0,
                            Notlar = "Ticket oluşturun ve teknik ekibe atayın",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 13,
                            Aktif = true,
                            Baslik = "Ödeme Yöntemleri",
                            DegiskenIceriyor = false,
                            Icerik = "Ödeme seçeneklerimiz şunlardır:\n\n• Kredi Kartı (Tek Çekim / Taksit)\n• Banka Havalesi / EFT\n• Kapıda Ödeme (Nakit / Kredi Kartı)\n\nHangi ödeme yöntemini tercih edersiniz?",
                            KategoriId = 6,
                            KullanimSayisi = 0,
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 14,
                            Aktif = true,
                            Baslik = "Fatura Talebi",
                            DegiskenIceriyor = false,
                            Icerik = "Faturanız sipariş tamamlandıktan sonra e-posta adresinize otomatik olarak gönderilecektir. Ayrıca hesabınızdan 'Siparişlerim' bölümünden de faturanızı indirebilirsiniz. Kurumsal fatura için fatura bilgilerinizi şimdi kaydedebilirim.",
                            KategoriId = 6,
                            KullanimSayisi = 0,
                            Notlar = "Kurumsal fatura için vergi no ve şirket unvanı alın",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        },
                        new
                        {
                            Id = 15,
                            Aktif = true,
                            Baslik = "Şikayet Alma",
                            DegiskenIceriyor = true,
                            Icerik = "Yaşadığınız olumsuz deneyim için özür dilerim {MusteriAdi}. Şikayetinizi en üst düzeyde önemsiyoruz. Lütfen durumu detaylı anlatır mısınız? Sorununuzu çözmek için elimden geleni yapacağım.",
                            KategoriId = 7,
                            KisaYol = "F6",
                            KullanimSayisi = 0,
                            Notlar = "Empatik olun, müşteriyi dinleyin, not alın",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 1
                        },
                        new
                        {
                            Id = 16,
                            Aktif = true,
                            Baslik = "Supervisor'e Yönlendirme",
                            DegiskenIceriyor = false,
                            Icerik = "Durumunuzu anlıyorum ve size en iyi şekilde yardımcı olmak istiyorum. Bu konuda yetkilim dahilinde yapabileceklerim sınırlı. Müdürümüzle görüştüreyim, size daha kapsamlı yardımcı olabilir. Müsait olana kadar kısa bir süre bekler misiniz?",
                            KategoriId = 7,
                            KullanimSayisi = 0,
                            Notlar = "Supervisor'e durumu özetleyin",
                            OlusturulmaTarihi = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Sira = 2
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri adı");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Müşteri adresi");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2")
                        .HasComment("Müşteri doğum tarihi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Müşteri e-posta adresi");

                    b.Property<bool>("GeciciKayit")
                        .HasColumnType("bit");

                    b.Property<int>("KayitDurumu")
                        .HasColumnType("int");

                    b.Property<bool>("KayitTamamlandi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Kayıt oluşturulma tarihi");

                    b.Property<int?>("MusteriTipi")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Müşteri hakkında notlar");

                    b.Property<string>("OzelNotlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Müşteri soyadı");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Müşteri telefon numarası");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Musteriler_Email");

                    b.HasIndex("TelefonNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Musteriler_TelefonNo");

                    b.ToTable("Musteriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            Adres = "İstanbul, Türkiye",
                            DogumTarihi = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet@email.com",
                            GeciciKayit = false,
                            KayitDurumu = 0,
                            KayitTamamlandi = true,
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Düzenli müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Yılmaz",
                            TelefonNo = "05551234567"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Adres = "Ankara, Türkiye",
                            DogumTarihi = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse@email.com",
                            GeciciKayit = false,
                            KayitDurumu = 0,
                            KayitTamamlandi = true,
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Notlar = "Yeni müşteri",
                            SonGuncelleme = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Kaya",
                            TelefonNo = "05559876543"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("CagriSuresi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriMemnuniyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Oncelik")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("OperatorId");

                    b.ToTable("MusteriAktiviteleri", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Etiket atama tarihi");

                    b.Property<int?>("AtayanOperatorId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriEtiketiId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Atama notları");

                    b.HasKey("Id");

                    b.HasIndex("AtamaTarihi");

                    b.HasIndex("AtayanOperatorId");

                    b.HasIndex("MusteriEtiketiId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("MusteriId", "MusteriEtiketiId")
                        .IsUnique()
                        .HasDatabaseName("IX_MusteriEtiketAtamalari_MusteriId_MusteriEtiketiId");

                    b.ToTable("MusteriEtiketAtamalari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Etiket açıklaması");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Etiket adı");

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Etiket aktif durumu");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Etiket oluşturulma tarihi");

                    b.Property<string>("RenkKodu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007bff")
                        .HasComment("Etiket renk kodu");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_MusteriEtiketleri_Ad");

                    b.ToTable("MusteriEtiketleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Yüksek değerli müşteriler",
                            Ad = "VIP Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#FFD700"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Düzenli olarak hizmet alan müşteriler",
                            Ad = "Düzenli Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#28a745"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Yeni kayıt olan müşteriler",
                            Ad = "Yeni Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#17a2b8"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Dikkatli yaklaşılması gereken müşteriler",
                            Ad = "Riskli Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#dc3545"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Sık sık şikayet eden müşteriler",
                            Ad = "Şikayetçi Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#fd7e14"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Hizmetlerden memnun olan müşteriler",
                            Ad = "Memnun Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#6f42c1"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kurumsal müşteriler",
                            Ad = "Kurumsal Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#20c997"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Bireysel müşteriler",
                            Ad = "Bireysel Müşteri",
                            Aktif = true,
                            OlusturulmaTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RenkKodu = "#6c757d"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("CalismaSaatiBaslangic")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CalismaSaatiBitis")
                        .HasColumnType("time");

                    b.Property<string>("DurumNotu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GununBaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GununBitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MevcutDurum")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SonDurumDegisikliği")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGiris")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_Email");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique()
                        .HasDatabaseName("IX_Operatorler_KullaniciAdi");

                    b.ToTable("Operatorler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "admin@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            MevcutDurum = 0,
                            Rol = "Admin",
                            Sifre = "admin123",
                            Soyad = "User",
                            Telefon = "05551111111"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mehmet",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 9, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 0, 0, 0),
                            Email = "mehmet@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "mehmet.demir",
                            MevcutDurum = 0,
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Demir",
                            Telefon = "05552222222"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fatma",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 30, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 30, 0, 0),
                            Email = "fatma@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "supervisor",
                            MevcutDurum = 0,
                            Rol = "Supervisor",
                            Sifre = "super123",
                            Soyad = "Özkan",
                            Telefon = "05553333333"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ali",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 9, 0, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 18, 0, 0, 0),
                            Email = "ali@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "operator1",
                            MevcutDurum = 0,
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Kaya",
                            Telefon = "05554444444"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Zeynep",
                            Aktif = true,
                            CalismaSaatiBaslangic = new TimeSpan(0, 8, 30, 0, 0),
                            CalismaSaatiBitis = new TimeSpan(0, 17, 30, 0, 0),
                            Email = "zeynep@cagrimerkezi.com",
                            KayitTarihi = new DateTime(2025, 8, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "operator2",
                            MevcutDurum = 0,
                            Rol = "Operator",
                            Sifre = "op123",
                            Soyad = "Çelik",
                            Telefon = "05555555555"
                        });
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorDurumGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2")
                        .HasComment("Durum bitiş zamanı");

                    b.Property<DateTime>("GecisZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Durum geçiş zamanı");

                    b.Property<int?>("IlgiliAramaLogId")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Durum değişikliği notu");

                    b.Property<string>("OncekiDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Önceki durum");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<bool>("OtomatikGecis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Otomatik geçiş mi?");

                    b.Property<string>("YeniDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Yeni durum");

                    b.HasKey("Id");

                    b.HasIndex("GecisZamani")
                        .HasDatabaseName("IX_OperatorDurumGecmisleri_GecisZamani");

                    b.HasIndex("IlgiliAramaLogId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("IX_OperatorDurumGecmisleri_OperatorId");

                    b.HasIndex("OperatorId", "GecisZamani")
                        .HasDatabaseName("IX_OperatorDurumGecmisleri_OperatorId_GecisZamani");

                    b.ToTable("OperatorDurumGecmisleri", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorGunlukDurumOzeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AraCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Ara çalışma süresi (dakika)");

                    b.Property<decimal>("CagrıdaGecenSure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Çağrıda geçen süre (dakika)");

                    b.Property<decimal>("EgitimSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Eğitim süresi (dakika)");

                    b.Property<decimal>("MolaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Mola süresi (dakika)");

                    b.Property<decimal>("MusaitSure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Müsait bekleme süresi (dakika)");

                    b.Property<decimal>("OgleYemegiSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Öğle yemeği süresi (dakika)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrtalamaAraCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Ortalama ara çalışma süresi (dakika)");

                    b.Property<decimal?>("OrtalamaCagriSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Ortalama çağrı süresi (dakika)");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2")
                        .HasComment("Özet tarihi");

                    b.Property<int>("ToplamCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Toplam çalışma süresi (dakika)");

                    b.Property<decimal>("ToplantiSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Toplantı süresi (dakika)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("IX_OperatorGunlukDurumOzetleri_OperatorId");

                    b.HasIndex("Tarih")
                        .HasDatabaseName("IX_OperatorGunlukDurumOzetleri_Tarih");

                    b.HasIndex("OperatorId", "Tarih")
                        .IsUnique()
                        .HasDatabaseName("IX_OperatorGunlukDurumOzetleri_OperatorId_Tarih");

                    b.ToTable("OperatorGunlukDurumOzetleri", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AktifCalismaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CozulenCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MusteriMemnuniyetPuani")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrtalamaCagriSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PerformansPuani")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamCagriSayisi")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamMolaSuresi")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("Tarih");

                    b.ToTable("OperatorPerformansKayitlari", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Randevu açıklaması");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Randevu başlığı");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2")
                        .HasComment("Randevu bitiş zamanı");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Bekliyor")
                        .HasComment("Randevu durumu");

                    b.Property<bool>("HatirlatmaAktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Hatırlatma aktif mi");

                    b.Property<bool>("HatirlatmaGonderildi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Hatırlatma gönderildi mi");

                    b.Property<int>("HatirlatmaSuresi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15)
                        .HasComment("Hatırlatma süresi (dakika)");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanOperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Randevu oluşturulma tarihi");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Normal")
                        .HasComment("Randevu önceliği");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuZamani")
                        .HasColumnType("datetime2")
                        .HasComment("Randevu tarihi ve saati");

                    b.Property<DateTime>("SonGuncelleme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Son güncelleme tarihi");

                    b.Property<string>("TamamlanmaNotu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Tamamlanma notu");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Randevu tipi");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_Randevular_Durum");

                    b.HasIndex("MusteriId")
                        .HasDatabaseName("IX_Randevular_MusteriId");

                    b.HasIndex("OlusturanOperatorId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("IX_Randevular_OperatorId");

                    b.HasIndex("RandevuZamani")
                        .HasDatabaseName("IX_Randevular_RandevuZamani");

                    b.HasIndex("RandevuZamani", "OperatorId")
                        .HasDatabaseName("IX_Randevular_RandevuZamani_OperatorId");

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.AramaLog", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonKullanim", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.MusteriAktiviteler", "Aktivite")
                        .WithMany()
                        .HasForeignKey("AktiviteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.CevapSablonu", "Sablon")
                        .WithMany("KullanimKayitlari")
                        .HasForeignKey("SablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivite");

                    b.Navigation("Musteri");

                    b.Navigation("Operator");

                    b.Navigation("Sablon");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonu", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.CevapSablonKategori", "Kategori")
                        .WithMany("Sablonlar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "OlusturanOperator")
                        .WithMany()
                        .HasForeignKey("OlusturanOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");

                    b.Navigation("OlusturanOperator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriAktiviteler", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Musteri");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketAtama", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "AtayanOperator")
                        .WithMany()
                        .HasForeignKey("AtayanOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.MusteriEtiketi", "MusteriEtiketi")
                        .WithMany("MusteriEtiketAtamalari")
                        .HasForeignKey("MusteriEtiketiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany("EtiketAtamalari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtayanOperator");

                    b.Navigation("Musteri");

                    b.Navigation("MusteriEtiketi");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorDurumGecmisi", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.AramaLog", "IlgiliAramaLog")
                        .WithMany()
                        .HasForeignKey("IlgiliAramaLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("DurumGecmisleri")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IlgiliAramaLog");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorGunlukDurumOzeti", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.OperatorPerformans", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany("PerformansKayitlari")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Randevu", b =>
                {
                    b.HasOne("CagriMerkeziUyg.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "OlusturanOperator")
                        .WithMany()
                        .HasForeignKey("OlusturanOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CagriMerkeziUyg.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("OlusturanOperator");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonKategori", b =>
                {
                    b.Navigation("Sablonlar");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.CevapSablonu", b =>
                {
                    b.Navigation("KullanimKayitlari");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Musteri", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("EtiketAtamalari");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.MusteriEtiketi", b =>
                {
                    b.Navigation("MusteriEtiketAtamalari");
                });

            modelBuilder.Entity("CagriMerkeziUyg.Models.Operator", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("DurumGecmisleri");

                    b.Navigation("PerformansKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
